export interface Cliente {
	Codigo: string;
	Descripcion: string;
	NombreFantasia: string;
	CategoriaIva: string;
	ListaPrecio?: string;
	Domicilio?: string;
	Cuit?: string;
	Activo?: number;
	Telefono?: string;
	ImporteDeuda: number;
	CategoriaIvaRelacion?: {
		Descripcion: string;
	};
	Calle: string;
	Numero: string;
	Piso: string;
	Departamento: string;
	ProvinciaCodigo: string;
	CodigoPostal: string;
	Localidad: string;
	ContactoNombre: string;
	Mail: string;
	TelefonoMovil: string;
	ContactoComercial: string;
	CodigoVendedor: string;
	Actualizado: number;
	SaldoNTCNoAplicado: number;
	LimiteCredito: number;
	CanalCodigo: string;
	FechaDeAlta: string;
	FechaDeBaja: string;
	TransporteCodigo: string;
	DirEntregaCalle: string;
	DirEntregaNumero: string;
	DirEntregaPiso: string;
	DirEntregaDpto: string;
	DirEntregaProvinciaCodigo: string;
	DirEntregaLocalidadCodigo: string;
	CondicionVentaCodigo: string;
	PorcentajeBonificacionGeneral: number;
	GrupoPercepcionIIBBCodigo: string;
	PorcentajePercepcionIIBB: number;
	GrupoCodigo: string;
	cant_facturas_impagas_max: number;
	ZonaCodigo: string;
	InvCuentaVentas: number | null;
	CliCuentaCredito: number | null;
	TipoDocumento: string;
	CodigoLocalidad: string;
}
