/**
 * Etapas del reseteo de base (opciones de desarrollador).
 * `tablas` va de hija a madre; las tablas que no existen en la base de la empresa se ignoran.
 * `requiere`: etapas que tienen que estar vacías o marcadas en la misma ejecución.
 * El orden del arreglo es el orden de borrado.
 */
const ETAPAS = [
  {
    id: 'facturas',
    label: 'Facturas y ventas',
    descripcion: 'Facturas, ventas a cuenta, órdenes de entrega y comisiones de vendedores.',
    tablas: [
      'orden_entrega_items',
      'orden_entrega_cabeza',
      'ventas_a_cuenta',
      'documentos_deuda',
      'comisionesitems',
      'comisionescabeza',
      'facturaitems',
      'facturacabeza',
    ],
    requiere: [],
  },
  {
    id: 'notas-credito',
    label: 'Notas de crédito',
    descripcion: 'Notas de crédito a clientes con sus ítems y valores.',
    tablas: ['notacreditovalores', 'notacreditoitems', 'notacreditocabeza'],
    requiere: [],
  },
  {
    id: 'notas-debito',
    label: 'Notas de débito',
    descripcion: 'Notas de débito a clientes.',
    tablas: ['notadebitoitems', 'notadebitocabeza'],
    requiere: [],
  },
  {
    id: 'recibos',
    label: 'Recibos de clientes',
    descripcion: 'Cobranzas: recibos, ítems imputados y valores.',
    tablas: ['recibosvalores', 'recibositems', 'reciboscabeza'],
    requiere: [],
  },
  {
    id: 'presupuestos',
    label: 'Presupuestos',
    descripcion: 'Presupuestos a clientes.',
    tablas: ['presupuestoitems', 'presupuestocabeza'],
    requiere: [],
  },
  {
    id: 'pedidos',
    label: 'Pedidos, preventas y remitos',
    descripcion: 'Pedidos, preventas de móviles, remitos y órdenes de carga.',
    tablas: [
      'pedidositems',
      'pedidoscabeza',
      'preventa_items',
      'preventa_cabeza',
      'remitos_items',
      'remitos_cabeza',
      'ordencargaitems',
      'ordencargacabeza',
    ],
    requiere: [],
  },
  {
    id: 'compras',
    label: 'Compras y pagos a proveedores',
    descripcion: 'Compras, gastos, órdenes de compra, pagos, notas de crédito y débito de proveedores.',
    tablas: [
      'comprasitems',
      'comprascabeza',
      'gastositems',
      'gastoscabeza',
      'prv_orden_compra_items',
      'prv_orden_compra',
      'proveedoresrecibosvalores',
      'proveedoresrecibositems',
      'proveedoresreciboscabeza',
      'proveedoresnotacreditovalores',
      'proveedoresnotacreditoitems',
      'proveedoresnotacreditocabeza',
      'proveedoresnotadebitoitems',
      'proveedoresnotadebitocabeza',
    ],
    requiere: [],
  },
  {
    id: 'caja',
    label: 'Caja y cheques',
    descripcion: 'Aperturas y cierres de caja, movimientos, arqueos y cheques.',
    tablas: [
      'caja_arqueo_detalle',
      'caja_movimientos',
      'caja_cabeza',
      'caja_cabeza_new',
      'cheques',
    ],
    requiere: [],
  },
  {
    id: 'stock',
    label: 'Movimientos de stock',
    descripcion: 'Historial de movimientos y ajustes. Deja la existencia de todos los productos en cero.',
    tablas: ['movimientospasajearticulos', 'movimientosstock'],
    requiere: [],
  },
  {
    id: 'contabilidad',
    label: 'Asientos contables',
    descripcion: 'Libro diario. No toca el plan de cuentas.',
    tablas: ['gmc_diario_general'],
    requiere: [],
  },
  {
    id: 'clientes',
    label: 'Clientes',
    descripcion: 'Clientes, descuentos, rutas y entregas asignadas.',
    tablas: [
      'clientes_descuentos',
      'rutas_clientes',
      'rutas_entrega_clientes',
      'tmp_ventas_clientes_periodos',
      'geolocalizacion',
      't_clientes',
    ],
    requiere: ['facturas', 'notas-credito', 'notas-debito', 'recibos', 'presupuestos', 'pedidos'],
  },
  {
    id: 'productos',
    label: 'Productos',
    descripcion: 'Artículos, composiciones, unidades, historial de costos y asignaciones a móviles y rutas.',
    tablas: [
      't_articulos_composicion',
      't_articulos_unidades_alternativas',
      't_articulos_costo_historial',
      't_articulosumoviles',
      't_articulosadescargartmp',
      't_relaciones_articulo_proveedor',
      'cargapordefecto',
      'rutas_articulos',
      'comisiones_vendedores',
      'ger_t_agrupaciones_grupos_articulos',
      't_articulos',
    ],
    requiere: ['facturas', 'notas-credito', 'pedidos', 'presupuestos', 'compras', 'stock'],
  },
  {
    id: 'proveedores',
    label: 'Proveedores',
    descripcion: 'Proveedores y sus retenciones. A los productos que queden se les quita el proveedor.',
    tablas: ['t_relaciones_articulo_proveedor', 'proveedores_retenciones', 't_proveedores'],
    requiere: ['compras'],
  },
  {
    id: 'temporales',
    label: 'Tablas temporales de informes',
    descripcion: 'Tablas tmp_* que usan los informes. Se regeneran solas.',
    tablas: [],
    prefijo: 'tmp_',
    requiere: [],
  },
];

const ETAPAS_DOCUMENTOS_CLIENTE = ['facturas', 'notas-credito', 'notas-debito', 'recibos'];

module.exports = { ETAPAS, ETAPAS_DOCUMENTOS_CLIENTE };
